version: '3.8'

services:
  task-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo_tasks?allowPublicKeyRetrieval=true&createDatabaseIfNotExists=true
      SPRING_DATASOURCE_DDL_AUTO: update
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATASOURCE_USERNAME: emmanuel
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todo_tasks
      POSTGRES_USER: emmanuel
      POSTGRES_PASSWORD: 12345678
      POSTGRES_INITDB_ARGS: "-A password"  # Initialization with password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "emmanuel" ]
      interval: 10s
      timeout: 5s
      retries: 5
