services:
  - type: web
    name: task-service
    runtime: docker
    plan: free  # Adjust as necessary
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: postgresql://emmanuel:U71bj8kbdb5rXJOLIepdKB3yi0j1qvyo@dpg-cq9106jv2p9s73cbp2fg-a/todo_tasks_uayo
      - key: SPRING_DATASOURCE_USERNAME
        value: emmanuel
      - key: SPRING_DATASOURCE_PASSWORD
        value: U71bj8kbdb5rXJOLIepdKB3yi0j1qvyo
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        value: "true"

databases:
  - name: todo-tasks-db
    databaseName: todo_tasks
    plan: free
    user: emmanuel

