services:
  - type: web
    name: task-service
    runtime: docker
    plan: free  # Adjust as necessary
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: todo-tasks-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: todo-tasks-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: todo-tasks-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        value: "true"
      - key: SPRING_MAIN_ALLOWED_BEAN_DEFINITION_OVERRIDING
        value: "true"

databases:
  - name: todo-tasks-db
    databaseName: todo_tasks
    plan: free
    user: emmanuel

